/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intelli_nav;

import io.javalin.Javalin;
import static io.javalin.apibuilder.ApiBuilder.*;

import intelli_nav.model.MovePayload;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        final RobotUtils robotUtils = new RobotUtils();
        robotUtils.moveMouse(100, 100);

        var app = Javalin.create(config -> {
            config.router.apiBuilder(() -> {
                path("v1", () -> {
                    path("inav", () -> {
                        path("move", () -> {
                            post(ctx -> {
                                var payload = ctx.bodyAsClass(MovePayload.class);
                                robotUtils.moveMouse(payload.x(), payload.y());
                                ctx.status(200);
                            });
                        });
                    });
                });
            });
        })
                .start(7070);
    }
}
